### PR TITLE
Make badges clickable and up to date

### PR DESCRIPTION
**Pull request by 0xpr03**
I didn't change the license stuff because you'd have to use a different system to always define "latest" as your crate revision.

### CODE REVIEW

**Comment by 0xpr03** [comment]
Also could you release 0.4 with tokio 1.X as version ?

**Comment by jsvana** [comment]
Thanks for updating! Sorry I missed this. 

> Also could you release 0.4 with tokio 1.X as version ?

Will do!

**Comment by jsvana** [comment]
0.4.0 is up on crates.io.

**Comment by 0xpr03** [comment]
Thanks!

**Pull request merged**
